# This is a test config file with 3 small examples for each output
# In order to test a certain output, change the mode and uncomment the corresponding input_files (marked with mode name)
# !!! Note that the functional element can be called both CRS (cis-regulatory sequence) and CRE (cir-regulatory element) 

# Specify the MPRA dataset
# All options: trans, sc, bulk
mode: trans

# Enter path to the corresponded fastq files
input_files:
#trans
  guide: "data/example_data/trans/guide.fastq.gz"
  bc: "data/example_data/trans/bc.fastq.gz"
  crs: "data/example_data/trans/crs.fastq.gz"
  crs_paired: "path/to/paired_crs.fastq.gz"

# #sc
  # guide: "data/example_data/sc/guide.fastq.gz"
  # bc: "data/example_data/sc/bc.fastq.gz"
  # crs: "data/example_data/sc/crs.fastq.gz"
  # crs_paired: "data/example_data/sc/crs_paired.fastq.gz"

# # bulk
  # guide: "path/to/guide.fastq.gz"
  # bc: "data/example_data/bulk/bc.fastq.gz"
  # crs: "data/example_data/bulk/crs.fastq.gz"
  # crs_paired: "data/example_data/bulk/crs_paired.fastq.gz" # Only specify if the the mode is bulk and there are 2 fastq files for crs

# Enter path to the reference files (either .csv or .fa)
references:
  reference_guide: "data/example_data/gRNA_seqs.csv"
  reference_crs: "data/example_data/GRE_seqs.fa"

# Enter output directory for the aligned bam files, CRS-BC association .csv file and .Rmd report
out_dir: "results/" 

# Specify n of threads for the bwa alignment
threads_bwa: 1

